apiVersion: v1
kind: Service
metadata:
  name: tournmgmt-service
  namespace: tournmgmt
  labels:
    app: tournmgmt
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 6070
      name: http
  selector:
    app: tournmgmt
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tournmgmt-ingress
  namespace: tournmgmt
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - tournmgmt.eve.toys
      secretName: tournmgmt-tls
  rules:
    - host: tournmgmt.eve.toys
      http:
        paths:
          - path: /
            backend:
              serviceName: tournmgmt-service
              servicePort: 6070
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tournmgmt
  namespace: tournmgmt
  labels:
    app: tournmgmt
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: tournmgmt
  template:
    metadata:
      labels:
        app: tournmgmt
    spec:
      containers:
        - name: tournmgmt
          image: registry.digitalocean.com/staker-registry/tournmgmt:1.<VERSION>
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              port: 6070
              path: /ping
            initialDelaySeconds: 30
            periodSeconds: 1
          livenessProbe:
            httpGet:
              port: 6070
              path: /ping
            periodSeconds: 5
            initialDelaySeconds: 10
          ports:
            - containerPort: 6070
              name: app
          env:
            - name: BASE_URL
              value: "https://tournmgmt.eve.toys"
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_URL
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: HISTORICAL_URL
              valueFrom:
                secretKeyRef:
                  name: historical-secrets
                  key: HISTORICAL_URL
            - name: HISTORICAL_USER
              valueFrom:
                secretKeyRef:
                  name: historical-secrets
                  key: HISTORICAL_USER
            - name: HISTORICAL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: historical-secrets
                  key: HISTORICAL_PASSWORD
            - name: ESI_CLIENT
              valueFrom:
                secretKeyRef:
                  name: esi-secrets
                  key: ESI_CLIENT
            - name: ESI_SECRET
              valueFrom:
                secretKeyRef:
                  name: esi-secrets
                  key: ESI_SECRET
            - name: ESI_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: esi-secrets
                  key: ESI_CALLBACK_URL
            - name: SUPERUSER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SUPERUSER
            - name: DISCORD_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DISCORD_WEBHOOK

