apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: regcred
  namespace: tournmgmt
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2RvY2tlci5wa2cuZ2l0aHViLmNvbSI6eyJ1c2VybmFtZSI6ImV2ZS1nYXR0IiwicGFzc3dvcmQiOiJnaHBfZmZLU3ExS3ZickhRcDVYejBjeWdKcFBmTVVVVlk3MGlUdjZoIiwiYXV0aCI6IlpYWmxMV2RoZEhRNloyaHdYMlptUzFOeE1VdDJZbkpJVVhBMVdIb3dZM2xuU25CUVprMVZWVlpaTnpCcFZIWTJhQT09In19fQ==

